name: ci workflow for python apptest
on:
  push:
    branches:
      - "main"
#creating jobs
jobs:
  mli10-python-app-test:
    runs-on: ubuntu-latest
    steps:
      - name: checking 
        run: python -V